---
- hosts: all
  remote_user: keith
  become: true

  tasks:
    - name: add yarn repo key
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present

    - name: add yarn repo source (touch)
      file:
        path: /etc/apt/sources.list.d/yarn.list
        state: touch

    - name: add yarn repo source (write)
      lineinfile:
        path: /etc/apt/sources.list.d/yarn.list
        line: "deb https://dl.yarnpkg.com/debian/ stable main"

    - name: install packages
      apt:
        name:
          - yarn
          - nginx
        state: present
        update_cache: true
      become: true

    - name: copy nginx config
      copy:
        src: nginx-conf
        dest: /etc/nginx/sites-available/keithzhang.com

    - name: symlink nginx config
      file:
        src: /etc/nginx/sites-available/keithzhang.com
        dest: /etc/nginx/sites-enabled/keithzhang.com
        state: link

    - name: remove default nginx config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: copy ssl certificate
      copy:
        src: keys/certificate.crt
        dest: /etc/ssl/mycert.crt

    - name: copy ssl key
      copy:
        src: keys/private.key
        dest: /etc/ssl/mycert.key
