---
- hosts: all
  remote_user: keith

  tasks:

    - git:
        repo: https://github.com/keithohno/keithzhang.com-management.git
        dest: /home/keith/keithzhang.com-management
        force: yes
        
    - name: chmod init script
      file: dest=/home/keith/keithzhang.com-management/host/init.sh mode=a+x

    - name: chmod deploy script
      file: dest=/home/keith/keithzhang.com-management/host/deploy.sh mode=a+x

    - name: add yarn repo
      command: ./init.sh
      args:
        chdir: /home/keith/keithzhang.com-management/host

    - name: install yarn
      apt:
        name: yarn
        state: present
        update_cache: true
      become: true

    - name: install nginx
      apt:
        name: nginx
      become: true

